# frozen_string_literal: true

source "https://rubygems.org"

gemspec

group :development do
    gem "rake", "~> 13.2.1"
    gem "rspec", "~> 3.13.0"
    gem "rubocop", "~> 1.75.2"
    gem "ruby-lsp-rake", require: false
    gem "ruby-lsp-rspec", require: false
end
