# frozen_string_literal: true

require "bundler/gem_tasks"
require "rake/testtask"

Rake::TestTask.new do |t|
    t.libs << "test"
    t.test_files = FileList["test/**/*_test.rb"]
end

require "rubocop/rake_task"

RuboCop::RakeTask.new

require "reek/rake/task"

Reek::Rake::Task.new

task default: %i[test rubocop]
