name: shapes
version: 1.0.0.0
github: "githubuser/shapes"
license: ISC
author: "AlterSabeh"
maintainer: "example@example.com"
copyright: "2025 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md
# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/shapes#readme>

verbatim:
  cabal-version: 3.8

language: GHC2024

dependencies:
  - base ^>=4.20.0.0
  - containers ^>=0.7

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - Shapes
    - Shapes.Base.Commons
    - Shapes.Base.Models
    - Shapes.Client.Shell

executables:
  shapes-app:
    main: Shapes/App/Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - shapes

tests:
  models-test: &models-test
    main: ModelsTest.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - shapes
      - hspec

  commons-test:
    <<: *models-test
    main: CommonsTest.hs
