#!/usr/bin/env ruby
# frozen_string_literal: true

require "shapes/base/models"
require "shapes/client/shell"

def main
    program = Runner.new

    circle = Circle.new(15.25)
    circle.color = "RED"
    circle.print_description

    program.run
end

main
