name: shapes
version: 1.0.0
description: "Collection of shapes and their properties"

environment:
  sdk: "^3.7.0"

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  shapes-app: shapes_app.dart
