comment_width = 80
edition = "2024"
float_literal_trailing_zero = "Always"
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
hard_tabs = false
imports_granularity = "Module"
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
max_width = 100
merge_derives = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
tab_spaces = 4
use_field_init_shorthand = true
